services:
  backend:
    build:
      context: ./gpt-writing-backend
      dockerfile: Dockerfile
    environment:
      - MONGO_DB_KEY=${MONGO_DB_KEY}
      - OPEN_AI_KEY=${OPEN_AI_KEY}
    volumes:
      - ./gpt-writing-backend:/app/backend-server
    ports:
      - 5001:5000

  frontend:
    build:
      context: ./gpt-writing-frontend
      dockerfile: Dockerfile
    volumes:
      - ./gpt-writing-frontend:/app/frontend-server
    ports:
      - 3000:3000
